# .github/workflows/node.js.yaml

# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node on ubuntu, macos and
# windows.
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [main, develop]
    # Or use branches-ignore.
  pull_request:
    branches: [main, develop]
    # Or use branches-ignore.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run ci
